### ISSUE TITLE
Does not work on macOS/linux

### ISSUE THREAD

**Issue by mrleblanc101** [ssmak/snippets-from-gist#1]
Hi,
You seem to assume people that will use this package are on PC.
Please use path normalization. macOS and linux use forward slash ( / ) for directory unlike windows backwards slash ( \ ). 
https://nodejs.org/api/path.html

**Comment by ssmak** [comment]
Hi, thanks for your report and advice!
I have tried to fix the path issue and tested on Linux. I haven't MacOS for test, but I think the behavior of Mac is same as Linux.

Please marked that the path issue is fixed on version 1.4.2 of this package.
