### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by TriMoon** [ssmak/snippets-from-gist#2]
You need to provide better documentation:
  - How the layout of the gist repo should be if there is any...
  - An example file (with content) in the gist that will be used as snippet.
  - Explain multi-snippet file usage if there is such feature.

These might sound like noob points to you but new users to snippets and gist using your package will need these info....

That said, keep up the good work :wink: :+1:

**Comment by ssmak** [comment]
Hey guy,  if you see the project description (README.md) on detail, you will find the example here https://gist.github.com/ssmak/607432b1d66401428a7bcf5be316f705
and know how to define the snippet by yourself. 
Moreover, this is absolutely NOT a start-up guide for snippet and Atom, and requires the user a basic knowledge for snippet usage in Atom. 
By the way, please try to contribute but NOT ONLY a request.

**Comment by TriMoon** [comment]
Thanks for the updated README :wink:
